### ISSUE TITLE
Integrate with CI

### ISSUE THREAD

**Issue by ThomasThelen** [theJollySin/mazelib#108]
It would be awesome to get this integrated with Travis and Codecov. One advantage is finding out which python versions break with updates.

**Comment by theJollySin** [comment]
Worked like a charm.  I haven't put badges on the master README yet, but the build built on my Travis page.

I don't see the code coverage popping up, but I'll find it.

Thanks for showing me the Travis system!  It's always fun to have a new toy to play with.

**Comment by ThomasThelen** [comment]
For the coverage stuff you have to deal with it over on https://codecov.io/ which is essentially a similar process to travis. After adding the repo, kick off a travis build and it should work!

**Comment by theJollySin** [comment]
Yeah, I got the codecov account working.  But...

It is including the tests in the lines of code being covered.  Which is pretty sloppy.  So I'm trying to find around that.

Thanks, again.

**Comment by ThomasThelen** [comment]
Ah apologies. Let me file an issue and I'll take care of it so you can see.

**Comment by ThomasThelen** [comment]
Ah apologies. Let me file an issue and I'll take care of it so you can see.
