### ISSUE TITLE
Cannot install the package with Poetry and Python ^3.6

### ISSUE THREAD

**Issue by espdev** [theJollySin/mazelib#112]
I'm trying to add mazelib as dependency in my project. I use [Poetry](https://python-poetry.org/) as packaging and dependency management tool.

My project supports Python `>=3.6, <4` (`^3.6`). And I cannot install mazelib from PyPI because its supported Python version is incompatible with my:

```
$ poetry add mazelib

Resolving dependencies...

[SolverProblemError]
The current project's Python requirement (^3.6) is not compatible with some of the required packages Python requirement:
  - mazelib requires Python >=3.3, !=3.8.* , !=3.9.*

Because mazelib (0.9.7) requires Python >=3.3, !=3.8.* , !=3.9.*
 and no versions of mazelib match >0.9.7,<0.10.0, mazelib is forbidden.
```

Poetry has a dependency resolver and forbid incompatible dependencies.

I want to ask, why you do not support Python 3.8 and 3.9? It would be reasonable to specify supported Python version as `>=3.3,<4` (`>=3.4,<4`, yes, I know about dropping 3.3 and support 3.8 in master).

**Comment by theJollySin** [comment]
I do not support Python v3.8 and v3.9 because the project depends heavily on Cython.

If you just want to play with `mazelib`, you could just grab the repo and delete all the *.pxd files before you install it.  That would probably work fine on later versions of Python.

But Cython changes a lot between different versions of Python and I have not had the time to build a Docker image for Python v3.8 to test it and see what needs to change.  That's basically what I'm missing: a convenient test env in Python 3.8.

The only other dependency is NumPy, which I think will probably work fine in Python v3.8.

**Comment by espdev** [comment]
>  That's basically what I'm missing: a convenient test env in Python 3.8.

You could use Travis CI and tox and create test environments for all python versions without creating and deploying it manually. For example, you can see how it works in my project:
https://github.com/espdev/csaps

See files `tox.ini` and `.travis.yaml`
Also the result: https://travis-ci.org/github/espdev/csaps/builds/667921578

If you want, I can try to implement Travis CI integration in your project and make PR.

**Comment by espdev** [comment]
It seems you already have travis CI.
https://github.com/theJollySin/mazelib/blob/master/.travis.yml
Then I don’t understand what the problem is. :)

**Comment by theJollySin** [comment]
Yeah, I already have things set up on Travis.  I suppose I can just bump the version and watch the Travis build.

I *suppose* the truth is that while my unit tests have good code coverage I don't really trust them to tell me if the project is working.  Perhaps that's just paranoia though.

It's probably worth a try.

**Comment by theJollySin** [comment]
Sorry, someone had these questions a while back and it appears I do support Python v3.8.

SO.  Sorry for being a little unclear.  But were you not able to install on v3.8?

**Comment by espdev** [comment]
@theJollySin 

I tried to install in Python 3.6, but the problem in Poetry dependency resolver. In my project I supports Python `>=3.6,<4`. I specifies it as `^3.6`. This specification is incompatible with your specification (`>=3.3, !=3.8.* , !=3.9.*`) because you do not support 3.9 (and 3.8 in pypi currently in version `0.9.7`).

**Comment by theJollySin** [comment]
I believe I can safely close this ticket.  Some time back, the `setup.py` was change to explicitly support Python 3.8:

    python_requires='>=3.4, <3.9 ',
