### ISSUE TITLE
Add a random seed as an input

### ISSUE THREAD

**Issue by jlarson200** [theJollySin/mazelib#115]
John, Thank you for sharing and creating a full feature Maze API!  I wanted to ask, is it possible to have a control random seed used with the maze creation functions?  Was hoping to use it for some machine learning attempts.  If so, how?  Thanks again Joe

**Comment by theJollySin** [comment]
Sorry, right now there isn't such an option.

Looking at this really quickly, it looks adding these four lines to the code would solve the problem:

```
import numpy as np
np.random.seed(123)
import random
random.seed(123)
```

So, if you need a random seed option, that's all you need to do.

I like this as a part of the API though.  It seems like a low effort feature that wouldn't take me too long to implement.  I'm going to leave this ticket open and just implement the solution.  It's a nice idea!

**Comment by theJollySin** [comment]
@jlarson200  Okay, I built this into the project for you as a new feature.

So, when you create the `Maze` object, you can set the random seed for the project simply by added an extra parameter:

`m = Maze(123)`

Or, at any time, you can set/reset the random seed by doing:

`Maze.set_seed(456)`

I hope that helps!

**Comment by jlarson200** [comment]
John,
Thank you so much for this change and super quick response. I do not have your skills, but please let me know if I can offer something in return?

On a side note, this API may be used in a school paper.   I will reference your site and follow the standard citations methods, is there anything else you would like to have noted?
Joe

________________________________

**Comment by theJollySin** [comment]
@jlarson200   Whatever the standard citation is will be fine, but thanks for asking!

What's the paper about (if you don't mind me asking)?
