### ISSUE TITLE
Maze as Matrix?

### ISSUE THREAD

**Issue by ThomasThelen** [theJollySin/mazelib#117]
Since every maze has an adjacency matrix representation; it would be interesting (and helpful) to see the graph as a matrix for further analysis (maybe I want to investigate the spectrum of a few particular mazes that I found interesting). This _could_ also be a viable serialization format for the maze if you want to consider saving/loading in the future.

What do you think about a method in the `Maze` class that returns something like a numpy matrix? It may be a little too esoteric to include though.

**Comment by theJollySin** [comment]
Sorry if I don't fully understand your question.  But let me try.

The `Maze` class already has an attribute `self.grid` which is already a NumPy matrix.  

This `Maze.grid` attribute is the way the maze is recorded in the state of the `Maze` object.  Is that what you were hoping for?

**Comment by theJollySin** [comment]
@ThomasThelen  Since `Maze.grid` exists, and the documentation provides several ways to plot the matrices in this library, I am just going to go ahead and close this ticket. Feel free to open a new one, if you have a more specific concern.
