### ISSUE TITLE
Register with PyPI

### ISSUE THREAD

**Issue by theJollySin** [theJollySin/mazelib#54]
It will be as easy as:

```
 python setup.py register
```

A nice description of the process can be found at:

http://www.scotttorborg.com/python-packaging/minimal.html
http://guide.python-distribute.org/quickstart.html#lay-out-your-project

**Comment by doctorcolossus** [comment]
Any word on this? I have no experience doing this either, but I'm not bad with Python in general. Let me know if there's anything I can do to assist.

**Comment by theJollySin** [comment]
Honestly, I didn't think anyone was interested.  The project still has some outstanding issues too.  Cellular Automaton barely works (here or anywhere else).  And I need to build up some more serious testing, because there are so many edge cases it's crazy. 

BUT, if you're interested, the project is now on PyPI!

https://pypi.org/project/mazelib/

So, you can now install it by simply doing: `pip install mazelib`.  Neat!

The project needs some TLC though, if you want to take a crack at it.  For instance, Ticket #93 is open, and I just can't reproduce it.

**Comment by theJollySin** [comment]
@doctorcolossus  Actually, man.  You know, what I could really use is someone else's eyeballs on this project.  I have these nagging suspicions that there are bugs left.  Like, maybe one of the Maze Generator/Solver algorithm works *most* of the time, but like 1 out of 50 times it just fails in some subtle/hard way.

I guess what I really need is another person trying to break stuff.

Just a thought.
Thanks!

**Comment by doctorcolossus** [comment]
Cool! I will see what I can do when I have time.

I'm in a software engineering class and our team's task is to write a Zork clone. The LAs (learning assistants) for the class sent us a link to your library and also asked us build maps using NetworkX. Our first user story was to generate mazes, so I whipped up a function to convert mazelib's output to NetworkX graphs. However, the LAs are really uptight about code coverage, and although they told us it would be good to use external libraries, anything we pull in has to be at > 95% code coverage. And apparently they hadn't checked that for mazelib themselves and are now saying they only sent us the link as an example... o_O WTF. Well, I ran mazelib's tests and I think coverage was around 85%. But so far we're just using Prim's method, which is fortunately at 100%.

Well, that's the story of what brought me to mazelib.
I haven't delved in too deeply yet, but it's an impressive collection of algorithms.
When I can find some spare time, I'll see if I can write some more tests. :)

**Comment by theJollySin** [comment]
@doctorcolossus  OKAY, code coverage is important.  Good to know.  I guess I need to run a coverage tool against my unit tests and see what pieces of my code aren't covered.  That's probably a good idea anyway.  I will open a ticket for that.

I don't *know* of any intermittent bugs at the moment.  But there were a ton of them while I was writing the first draft of all these algorithms and I just can't shake the feeling that there are still some floating around.

**Comment by doctorcolossus** [comment]
Wow, that's awesome! :grinning:
Thank you so much!

**Comment by theJollySin** [comment]
@doctorcolossus  Just an update, the code test coverage is over 95% now.  Hope that helps. :)

**Comment by theJollySin** [comment]
@doctorcolossus   Unrelated, but just FYI.

I am going to remove the WallFollower solver algorithm and slightly modify Chain (as it uses WallFollower).

Basically, I think the API for mazelib would be simpler to understand if the user didn't have to know which maze generators could work with which maze solvers.  So I am going to support all maze generating algorithms going forward, but only maze solving algorithms which are universal (work for all mazes).

Just FYI.  Change coming soon.
