### ISSUE TITLE
add Documentation: Installation

### ISSUE THREAD

**Issue by theJollySin** [theJollySin/mazelib#55]
setup.py.... blah, blah, blah

Surely someone else has already written this up much better than I will. 

Also, perhaps I should wait until I am integrated into PyPI?

**Comment by theJollySin** [comment]
I have a separate ticket for PyPI, and now that I have abandoned Cython the installation is pretty trivial.

**Comment by Eric-Vignola** [comment]
have you considered Numba?

**Comment by theJollySin** [comment]
Oh, I didn't abandon Cython because it didn't make things faster. I abandoned it because most of the (admittedly small) user base were using mazelib as a reference for how these algorithms work. So all the effort to translate the project to Cython was actually making the project less useful to people.

Otherwise, Cython, Numba, or even just writing the algorithms in C would be more performant.
