### ISSUE TITLE
Re-Cythonize as pxd

### ISSUE THREAD

**Issue by theJollySin** [theJollySin/mazelib#91]
I don't know why I didn't think of this before.

I preferred this project as Cython, but the (very small) user base mostly just seemed interested in reading how the algorithms work.

So I can leave the algorithms in pure (oh so readable) Python, but add *.pxd files and build out the setup.py so the project actually builds into Cython, thus getting my back 99% of my performance.

Cython, coming to the rescue again.

**Comment by Eric-Vignola** [comment]
I forget if i've mentionned this before, but have you considered numba
<https://numba.pydata.org/>in lieu of cython? If not i would recommend
looking into it. Generating static .pyd's is practically trivial
<https://numba.pydata.org/numba-doc/dev/user/pycc.html> and performance
often surpasses cython.

**Comment by theJollySin** [comment]
I *haven't* tried numba, actually. I should play with it. But would is there anyway to separate the Numba code from the pure Python, so people that want just want to learn how a maze algorithm works can easilly read pure Python without having to see how I use Cython/Numba in the background to bump performance?

One of my design goals is to make sure people can easily understand the algorithms themselves, as some people are more interested in that than they are actually using mazelib.

Thanks!

**Comment by Eric-Vignola** [comment]
Yes, it's probably simpler with numba than it is with cython.

About Numba: it specializes in just-in-time compilation, so you never
really need .pyd's, everything remains pure python. I haven't looked at
your code but if you kept everything as is and added @jit decorators to
your functions, with no optimization, you'd get a small speed boost. Then
when you dig deeper you can optimize your code to not need to handle any
python objects and use the @njit decorator, and then you'll be at cython
speed if not faster. Dig even deeper and you can start using the GPU to
really start cooking at lightspeed.

To write your code in such a way that your users don't need to have
numpy+numba installed, you can use the @cc.export decorator to compile
ahead of time. That will generate a .pyd.

When you look at numba code, it looks very much like cython without the
cython specific declarations. As a matter of fact, if you took an existing
cython script, removed everything cython about it and used the @njit
decorator, your function would run just as fast cython.

Anyways, give it a whirl! When i tried it i immediately fell in love and
converted all my cython code.

**Comment by theJollySin** [comment]
Okay, a first pass of Cythonizing the library seems to lead to about 20-50% speed improvement.  I'm not sure that is a big enough improvement to warrant the overhead and extra library install for a casual user.

The problem appears to be that I was utilizing NumPy correctly, so most of the heavy-lifting was done there instead of in pure Python.

I may try numba next, to see if that does any better.

**Comment by theJollySin** [comment]
Okay, this is a heavily constrained problem. I want to speed up the performance of the code while still allowing it to be readable for folks who aren't Python experts. So, there's my constraint.

1. It looks like if I peel open all my class/inheritance structure and ditch my API the fastest (easy) option is to use numba's @jit decorators. Though I want my API to remain the same.
2. The next fastest option is to totally re-write my code base using Cython an C memory-views. This is blisteringly fast, but the code is basically unreadable to people who aren't cozy with Cython.
3. With only a 25% speed bump, I can leave the Python code 100% untouched and use external Cython *.pxd header files.

So, options 1 and 2 are what I would normally do in production code. But I will fall back on option 3 for now.  Oh well.

If performance was really my top concern, I would re-write the algoritms in C and just build a Python API for them. But that completely loses my readability goals.

**Comment by Eric-Vignola** [comment]
Cool, well at least you tried  :)

For speed, did you try declaring function signatures and use
parallelization? Declaring your function signatures makes a difference.
Unfortunately parallel doesn't work with 2.7, but for python3 is makes a
huge difference.

ex:

*from numba import jit, njit, prange, float64
import numpy as np

# 1) straight up @jit
@jit
def test1(A):
    s = 0
    for i in range(A.shape[0]):
        s += A[i]**0.5
    return s

# 2) nopython=True with function signatures
@njit('float64(float64[:])')
def test2(A):
    s = 0
    for i in range(A.shape[0]):
        s += A[i]**0.5
    return s

# 3) With parallization
@njit('float64(float64[:])', parallel=True)
def test3(A):
    s = 0
    for i in prange(A.shape[0]):
        s += A[i]**0.5
    return s*

*data = np.random.random(10**7) # 10 million floats to sum and do a square root
# Test1: 0.09084248542785645s   -nominal
# Test2: 0.028714656829833984s  ~3x speed boost over nominal
# Test3: 0.015623092651367188s  ~6x speed boost over nominal*
